version: '2'
services:
  streaming-host:
    image: moellerdi/stream
    environment:
      INPUT_AUDIO_STREAM: /dev/zero
      INPUT_AUDIO_FORMAT: s16le

      INPUT_VIDEO_STREAM: http://octopi.local:8080/?action=stream
      INPUT_VIDEO_FORMAT: mjpeg

      OUTPUT_ACODEC: aac
      OUTPUT_VCODEC: h264

    command:
    - <your-key>